# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


stages:
- stage: Build
  displayName: Build
  jobs:  
  - job: Build
    displayName: Build job

    pool:
      name: 'Default'

    steps:
      - script: echo "Starting Build"
      # - script: Write-Error "file path not found"
      #   displayName: Publish to artifact services
  
- stage: DeploymentStage
  displayName: Deploy
  - stage: deploy
  jobs:
  - deployment: DeployWeb
    displayName: deploy Web App
    pool:
      vmImage: 'Ubuntu-16.04'
    # creates an environment if it doesn't exist
    environment: 'harshit-env'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello world

- stage: TestingStage
  displayName: TestStage
  jobs:
  - job: Test
    displayName: Test Code
    pool:
      name: 'Default'
    steps:
    - checkout: none
    - script: echo "Test project"
    # - script: Write-Error "Can't test, sorry!"
    #   displayName: Test

- stage: PublishTestResults
  displayName: Publish Test Results
  jobs:
  - job: Publish
    displayName: Publishing Test Results
    pool:
      name: 'Default'
    steps:
    - script: echo "Publish Test Results"

- stage: MakingUserStage
  displayName: Making User
  jobs:
  - job: MakeUser
    displayName: Building AI users
    pool:
      name: 'Default'
    steps:
    - checkout: none
    - script: echo "Building AI users for project"
    # - script: Write-Error "Can't make a user dude, what are you thinking!"
    #   displayName: Build AI bots

- stage: MakeThemPay
  displayName: Make AI pay
  jobs:
  - job: MakeAIbotspay
    displayName: Make AI bots pay
    pool:
      name: 'Default'
    steps:
    - checkout: none
    - script: echo "Making payment"
    # - script: Write-Error "Seriously?"
    #   displayName: Make payment