# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


stages:
- stage: Build
  displayName: Build
  jobs:  
  - job: Build
    displayName: Build job

    pool:
      name: 'Default'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'

      - script: |
          npm install
          npm run build
          displayName: 'npm install and build'

      # - script: Write-Error "file path not found"
      #   displayName: Publish to artifact services
  
- stage: DeploymentStage
  displayName: Prod
  jobs:
  - job: Deploy
    displayName: Deploy to kubernetes
    pool:
      name: 'Default'
    steps:
    - checkout: none
    - script: echo "Deploy project"
    # - script: Write-Error "Can't deploy, sorry!"
    #   displayName: Deploy

- stage: TestingStage
  displayName: TestStage
  jobs:
  - job: Test
    displayName: Test Code
    pool:
      name: 'Default'
    steps:
    - checkout: none
    - script: echo "Test project"
    - script: Write-Error "Can't test, sorry!"
      displayName: Test

- stage: MakingUserStage
  displayName: Making User
  jobs:
  - job: MakeUser
    displayName: Building AI users
    pool:
      name: 'Default'
    steps:
    - checkout: none
    - script: echo "Building AI users for project"
    - script: Write-Error "Can't make a user dude, what are you thinking!"
      displayName: Build AI bots

- stage: MakeThemPay
  displayName: Make AI pay
  jobs:
  - job: MakeAIbotspay
    displayName: Make AI bots pay
    pool:
      name: 'Default'
    steps:
    - checkout: none
    - script: echo "Making payment"
    - script: Write-Error "Seriously?"
      displayName: Make payment