# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


stages:
- stage: Build
  displayName: Build
  jobs:  
  - job: Build
    displayName: Build job

    pool:
      name: 'Default'

    steps:
      - script: echo "Starting Build"
        displayName: Deploy
      # - script: Write-Error "file path not found"
      #   displayName: Publish to artifact services
  
- stage: DeploymentStage
  displayName: Prod
  jobs:
  - job: Deploy
    displayName: Deploy to kubernetes
    pool:
      name: 'Default'
    steps:
    - checkout: none
    # - script: Write-Error "Can't deploy, sorry!"
    #   displayName: Deploy
    # - script: Write-Error "Can't deploy, sorry!"
    #   displayName: Deploy

- stage: TestingStage
  displayName: TestStage
  jobs:
  - job: Test
    displayName: Test Code
    pool:
      name: 'Default'
    steps:
    - checkout: none
    - script: echo "Test project"
    # - script: Write-Error "Can't test, sorry!"
    #   displayName: Test